/**
 * KISAN COMPASS — Guided Judge Proof Engine (Stage 12)
 * 
 * Orchestrates a structured 8-checkpoint walkthrough of real application state for judges.
 * Zero marketing slides. Pure interactive inspection of living deterministic systems.
 */

import { JudgeCheckpoint } from '../types/truth';

export const JUDGE_CHECKPOINTS: JudgeCheckpoint[] = [
  {
    id: 'JUDGE-CP-1',
    index: 1,
    title: 'Checkpoint 1: The Farm Digital Twin',
    subtitle: 'Persistent Farm State & Spatial Ground Truth',
    keyAssertion: 'KISAN COMPASS is a persistent farm twin and agronomic memory, not a stateless LLM chatbot.',
    honestBoundary: 'Field geometry and soil layers are anchored to ICAR Station UP-KN-892 and farmer ground records.',
    demonstrationInstruction: 'Inspect Field 07 (Wheat HD-2967, 2.4 Acres). Note active GDD thermal accumulation (1,845 / 1,950 GDD) and soil moisture layers.',
    actionType: 'NAVIGATE',
    targetTab: 'compass',
    expectedOutcome: 'Living 3D Farm Twin rendered with real-time agronomic telemetry and crop stage indicators.',
  },
  {
    id: 'JUDGE-CP-2',
    index: 2,
    title: 'Checkpoint 2: The Decision & Boundary',
    subtitle: 'Mathematical Decision Boundary (Why & What Changes Mind)',
    keyAssertion: 'The recommendation (SELL NOW) is not an opaque AI output; it is a deterministic optimization against weather downside risk.',
    honestBoundary: 'Decision sensitivity explicitly declares: if rain probability falls below 41%, recommendation flips to WAIT.',
    demonstrationInstruction: 'Click "WHY" to inspect the Grounded Explanation, and examine the sensitivity boundary conditions.',
    actionType: 'OPEN_MODAL',
    targetTab: 'compass',
    targetModal: 'CALCULATION_TRACE',
    expectedOutcome: 'Zero-hallucination explanation grounded in APMC prices (₹2,380), storm risk (68%), and dedicated freight (₹1,340).',
  },
  {
    id: 'JUDGE-CP-3',
    index: 3,
    title: 'Checkpoint 3: Counterfactual Simulation',
    subtitle: 'Probabilistic Quantile Spread (What-If Fan)',
    keyAssertion: 'The future is modeled as a distribution (P10/P50/P90), not a single point prediction.',
    honestBoundary: 'Moving the time horizon from Day 0 to Day 14 widens the uncertainty fan deterministically based on historical APMC volatility.',
    demonstrationInstruction: 'Navigate to What-If tab. Drag the time slider to +5 Days to observe the post-storm price upside (+₹40) versus rain dockage penalty (−₹3,838).',
    actionType: 'NAVIGATE',
    targetTab: 'what-if',
    targetModal: 'WHAT_IF',
    expectedOutcome: 'Live recalculation of net realizations and utility scores without page reloads or fabricated numbers.',
  },
  {
    id: 'JUDGE-CP-4',
    index: 4,
    title: 'Checkpoint 4: Trace This Decision & Prove Numbers',
    subtitle: 'End-to-End Decision Lineage & Arithmetic Substitution',
    keyAssertion: 'Every single quantitative claim can be traced back to exact source contracts, formulas, and raw observations.',
    honestBoundary: 'Clicking [ PROVE THIS NUMBER ] displays raw arithmetic substitution with no hidden constants or secret heuristics.',
    demonstrationInstruction: 'Open [ TRACE THIS DECISION ] from the recommendation card, or click [ PROVE THIS NUMBER ] on any metric card.',
    actionType: 'OPEN_MODAL',
    targetTab: 'compass',
    targetModal: 'JUDGE_PROOF',
    expectedOutcome: '12-stage interactive lineage tree from Doppler radar to mandi receipt and evaluation hash.',
  },
  {
    id: 'JUDGE-CP-5',
    index: 5,
    title: 'Checkpoint 5: Break the System (Failure Simulator)',
    subtitle: 'Graceful Degradation & Autonomous Fallback',
    keyAssertion: 'When external APIs fail, KISAN COMPASS does not invent hallucinated values or crash; it downgrades to CACHED with lower confidence.',
    honestBoundary: 'Demonstrates LIVE → CACHED → BASELINE → UNKNOWN resilience protocol.',
    demonstrationInstruction: 'Trigger Weather Failure from the Resilience Drawer. Watch system downgrade weather to CACHED, penalize assurance, and retain last verified state.',
    actionType: 'TRIGGER_SIMULATION',
    targetTab: 'compass',
    targetModal: 'FAILURE_DRAWER',
    expectedOutcome: 'System status updates to CACHED; Decision Assurance drops to MODERATE; explanation explicitly notes degraded telemetry.',
  },
  {
    id: 'JUDGE-CP-6',
    index: 6,
    title: 'Checkpoint 6: Human Farmer Authority & Memory',
    subtitle: 'Veto Rights & Bayesian Preference Adaptation',
    keyAssertion: 'The farmer holds absolute authority. The system never executes autonomous actions without human authorization.',
    honestBoundary: 'Rejection updates the farmer preference weighting profile from recorded choices (γ = 0.68) — the system adapts preferences, not "AI self-learning".',
    demonstrationInstruction: 'Review the Decision Memory ledger in Decisions tab. Inspect how historical approvals and rejections calibrate risk aversion.',
    actionType: 'NAVIGATE',
    targetTab: 'decisions',
    targetModal: 'DECISION_REPLAY',
    expectedOutcome: 'Auditable preference dimension breakdown across Risk, Cash Urgency, Weather Skepticism, and Storage Access.',
  },
  {
    id: 'JUDGE-CP-7',
    index: 7,
    title: 'Checkpoint 7: Field Execution Intelligence',
    subtitle: 'Operational Feasibility, Checklist & Deviation Guard',
    keyAssertion: 'A recommendation is only useful if it can be physically executed under field, labor, and logistics constraints.',
    honestBoundary: 'The system distinguishes between planned actions and physically verified real-world events.',
    demonstrationInstruction: 'Open the Execution Center. Walk through the 5-step operational checklist (Readiness, Crew Booking, Transport, Harvest, Mandi Sale).',
    actionType: 'OPEN_MODAL',
    targetTab: 'compass',
    targetModal: 'EXECUTION_CENTER',
    expectedOutcome: 'Real-time feasibility matrix (88%) and deviation triggers protecting against price drops and transit delays.',
  },
  {
    id: 'JUDGE-CP-8',
    index: 8,
    title: 'Checkpoint 8: Outcome Calibration & Evaluation Lab',
    subtitle: 'Verifiable Evaluation Lineage & Anti-Leakage Guard',
    keyAssertion: 'The system rigorously self-audits whether past predictions matched physical reality, with zero future information leakage.',
    honestBoundary: 'If sample size is small (N < 30), the system explicitly flags sample size limits rather than manufacturing synthetic perfection.',
    demonstrationInstruction: 'Open the Evaluation Lab. Filter by REAL_ONLY vs INCLUDE_DEMO, inspect the Exclusion Ledger, and verify the immutable SHA-256 run hash.',
    actionType: 'OPEN_MODAL',
    targetTab: 'decisions',
    targetModal: 'EVALUATION_LAB',
    expectedOutcome: 'Step-by-step arithmetic proof of 81.8% Interval Coverage and ₹74.3/qtl MAE across 11 eligible observations.',
  },
];
